[platformio]
default_envs = esp32-c3

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino@^2.3.0

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1

[env:ttgo-t-display]
platform = espressif32
board = esp32dev
build_flags = -D BOARD_TTGO_TDISPLAY

[env:ttgo-t-display-s3]
platform = espressif32
board = esp32-s3-devkitc-1
build_flags = -D BOARD_TTGO_TDISPLAY_S3
