[platformio]
default_envs = esp32-c3

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino@^2.3.0
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit PCD8544 Nokia 5110 LCD library@^2.3.0
  bodmer/TFT_eSPI@^2.5.43

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1

[env:ttgo-t-display]
platform = espressif32
board = esp32dev
build_flags = -D BOARD_TTGO_TDISPLAY -D USER_SETUP_LOADED=1 -D ST7789_DRIVER -D TFT_WIDTH=135 -D TFT_HEIGHT=240 -D TFT_MISO=-1 -D TFT_MOSI=19 -D TFT_SCLK=18 -D TFT_CS=5 -D TFT_DC=16 -D TFT_RST=23 -D TFT_BL=4 -D LOAD_GLCD -D LOAD_FONT2 -D LOAD_FONT4 -D SPI_FREQUENCY=40000000

[env:ttgo-t-display-s3]
platform = espressif32
board = esp32-s3-devkitc-1
build_flags = -D BOARD_TTGO_TDISPLAY_S3 -D USER_SETUP_LOADED=1 -D ST7789_DRIVER -D TFT_WIDTH=170 -D TFT_HEIGHT=320 -D TFT_MISO=-1 -D TFT_MOSI=17 -D TFT_SCLK=18 -D TFT_CS=6 -D TFT_DC=7 -D TFT_RST=5 -D TFT_BL=38 -D LOAD_GLCD -D LOAD_FONT2 -D LOAD_FONT4 -D SPI_FREQUENCY=40000000
